apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdb-deployment
  labels:
    app: duckdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: duckdb
  template:
    metadata:
      labels:
        app: duckdb
    spec:
      containers:
      - name: duckdb
        image: elimayost/nyc:latest
        command: ["sleep"]
        args: ["infinity"]

